import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class PetBreedsService {

  dogBreeds: any;
  catBreeds: any;
  types: any;

  constructor() {
    this.types = [
      { label: "Cat", value: "Cat" },
      { label: "Dog", value: "Dog" }
    ];

    this.dogBreeds = [{ label: "Affenpinscher", value: "Affenpinscher" },
    { label: "Afghan Hound", value: "Afghan Hound" },
    { label: "Aidi", value: "Aidi" },
    { label: "Airedale Terrier", value: "Airedale Terrier" },
    { label: "Akbash", value: "Akbash" },
    { label: "Akita (dog)|Akita", value: "Akita (dog)|Akita" },
    { label: "Alano Español", value: "Alano Español" },
    { label: "Alapaha Blue Blood Bulldog", value: "Alapaha Blue Blood Bulldog" },
    { label: "Sled dog#Alaskan husky|Alaskan husky", value: "Sled dog#Alaskan husky|Alaskan husky" },
    { label: "Alaskan Klee Kai", value: "Alaskan Klee Kai" },
    { label: "Alaskan Malamute", value: "Alaskan Malamute" },
    { label: "Alopekis", value: "Alopekis" },
    { label: "Alpine Dachsbracke", value: "Alpine Dachsbracke" },
    { label: "American Bulldog", value: "American Bulldog" },
    { label: "American Bully", value: "American Bully" },
    { label: "American Cocker Spaniel", value: "American Cocker Spaniel" },
    { label: "American English Coonhound", value: "American English Coonhound" },
    { label: "American Eskimo Dog", value: "American Eskimo Dog" },
    { label: "American Foxhound", value: "American Foxhound" },
    { label: "American Hairless Terrier", value: "American Hairless Terrier" },
    { label: "American Pit Bull Terrier", value: "American Pit Bull Terrier" },
    { label: "American Staffordshire Terrier", value: "American Staffordshire Terrier" },
    { label: "American Water Spaniel", value: "American Water Spaniel" },
    { label: "Anatolian Shepherd Dog", value: "Anatolian Shepherd Dog" },
    { label: "Andalusian Hound", value: "Andalusian Hound" },
    { label: "Anglo-Français de Petite Vénerie", value: "Anglo-Français de Petite Vénerie" },
    { label: "Appenzeller Sennenhund", value: "Appenzeller Sennenhund" },
    { label: "Ariegeois", value: "Ariegeois" },
    { label: "Armant (dog)|Armant", value: "Armant (dog)|Armant" },
    { label: "Armenian Gampr dog", value: "Armenian Gampr dog" },
    { label: "Artois Hound", value: "Artois Hound" },
    { label: "Australian Cattle Dog", value: "Australian Cattle Dog" },
    { label: "Australian Kelpie", value: "Australian Kelpie" },
    { label: "Australian Shepherd", value: "Australian Shepherd" },
    { label: "Australian Stumpy Tail Cattle Dog", value: "Australian Stumpy Tail Cattle Dog" },
    { label: "Australian Terrier", value: "Australian Terrier" },
    { label: "Austrian Black and Tan Hound", value: "Austrian Black and Tan Hound" },
    { label: "Austrian Pinscher", value: "Austrian Pinscher" },
    { label: "Azawakh", value: "Azawakh" },
    { label: "Bakharwal dog", value: "Bakharwal dog" },
    { label: "Banjara Hound", value: "Banjara Hound" },
    { label: "Barbado da Terceira", value: "Barbado da Terceira" },
    { label: "Barbet (dog)|Barbet", value: "Barbet (dog)|Barbet" },
    { label: "Basenji", value: "Basenji" },
    { label: "Basque Shepherd Dog", value: "Basque Shepherd Dog" },
    { label: "Basset Artésien Normand", value: "Basset Artésien Normand" },
    { label: "Basset Bleu de Gascogne", value: "Basset Bleu de Gascogne" },
    { label: "Basset Fauve de Bretagne", value: "Basset Fauve de Bretagne" },
    { label: "Basset Hound", value: "Basset Hound" },
    { label: "Bavarian Mountain Hound", value: "Bavarian Mountain Hound" },
    { label: "Beagle", value: "Beagle" },
    { label: "Beagle-Harrier", value: "Beagle-Harrier" },
    { label: "Groenendael dog|Belgian Shepherd Dog: Groenendael", value: "Groenendael dog|Belgian Shepherd Dog: Groenendael" },
    { label: "Laekenois dog|Belgian Shepherd Dog: Laekenois", value: "Laekenois dog|Belgian Shepherd Dog: Laekenois" },
    { label: "Malinois dog|Belgian Shepherd Dog: Malinois", value: "Malinois dog|Belgian Shepherd Dog: Malinois" },
    { label: "Tervuren dog|Belgian Shepherd Dog: Tervuren", value: "Tervuren dog|Belgian Shepherd Dog: Tervuren" },
    { label: "Bearded Collie", value: "Bearded Collie" },
    { label: "Beauceron", value: "Beauceron" },
    { label: "Bedlington Terrier", value: "Bedlington Terrier" },
    { label: "Bergamasco Shepherd", value: "Bergamasco Shepherd" },
    { label: "Berger Picard", value: "Berger Picard" },
    { label: "Bernese Mountain Dog", value: "Bernese Mountain Dog" },
    { label: "Bhotia dog|Bhotia", value: "Bhotia dog|Bhotia" },
    { label: "Bichon Frisé", value: "Bichon Frisé" },
    { label: "Billy (dog)|Billy", value: "Billy (dog)|Billy" },
    { label: "Black and Tan Coonhound", value: "Black and Tan Coonhound" },
    { label: "Black Norwegian Elkhound", value: "Black Norwegian Elkhound" },
    { label: "Black Russian Terrier", value: "Black Russian Terrier" },
    { label: "Black Mouth Cur", value: "Black Mouth Cur" },
    { label: "Bloodhound", value: "Bloodhound" },
    { label: "Blue Lacy", value: "Blue Lacy" },
    { label: "Blue Picardy Spaniel", value: "Blue Picardy Spaniel" },
    { label: "Bluetick Coonhound", value: "Bluetick Coonhound" },
    { label: "Boerboel", value: "Boerboel" },
    { label: "Bohemian Shepherd", value: "Bohemian Shepherd" },
    { label: "Bolognese (dog)|Bolognese", value: "Bolognese (dog)|Bolognese" },
    { label: "Border Collie", value: "Border Collie" },
    { label: "Border Terrier", value: "Border Terrier" },
    { label: "Borzoi", value: "Borzoi" },
    { label: "Barak hound|Bosnian Coarse-haired Hound", value: "Barak hound|Bosnian Coarse-haired Hound" },
    { label: "Boston Terrier", value: "Boston Terrier" },
    { label: "Bouvier des Ardennes", value: "Bouvier des Ardennes" },
    { label: "Bouvier des Flandres", value: "Bouvier des Flandres" },
    { label: "Boxer (dog)|Boxer", value: "Boxer (dog)|Boxer" },
    { label: "Boykin Spaniel", value: "Boykin Spaniel" },
    { label: "Bracco Italiano", value: "Bracco Italiano" },
    { label: "Braque d'Auvergne", value: "Braque d'Auvergne" },
    { label: "Ariege Pointer|Braque de l'Ariège", value: "Ariege Pointer|Braque de l'Ariège" },
    { label: "Braque du Bourbonnais", value: "Braque du Bourbonnais" },
    { label: "Braque Francais", value: "Braque Francais" },
    { label: "Braque Saint-Germain", value: "Braque Saint-Germain" },
    { label: "Briard", value: "Briard" },
    { label: "Briquet Griffon Vendéen", value: "Briquet Griffon Vendéen" },
    { label: "Brittany dog|Brittany", value: "Brittany dog|Brittany" },
    { label: "Broholmer", value: "Broholmer" },
    { label: "Bruno Jura Hound", value: "Bruno Jura Hound" },
    { label: "Griffon Bruxellois|Brussels Griffon", value: "Griffon Bruxellois|Brussels Griffon" },
    { label: "Bucovina Shepherd Dog", value: "Bucovina Shepherd Dog" },
    { label: "Bull Arab", value: "Bull Arab" },
    { label: "Bull Terrier", value: "Bull Terrier" },
    { label: "Bulldog", value: "Bulldog" },
    { label: "Bullmastiff", value: "Bullmastiff" },
    { label: "Bully Kutta", value: "Bully Kutta" },
    { label: "Burgos Pointer", value: "Burgos Pointer" },
    { label: "Cairn Terrier", value: "Cairn Terrier" },
    { label: "Campeiro Bulldog", value: "Campeiro Bulldog" },
    { label: "Canaan Dog", value: "Canaan Dog" },
    { label: "Canadian Eskimo Dog", value: "Canadian Eskimo Dog" },
    { label: "Cane Corso", value: "Cane Corso" },
    { label: "Cane Paratore", value: "Cane Paratore" },
    { label: "Cantabrian Water Dog", value: "Cantabrian Water Dog" },
    { label: "Can de Palleiro", value: "Can de Palleiro" },
    { label: "Cão da Serra de Aires", value: "Cão da Serra de Aires" },
    { label: "Cão de Castro Laboreiro", value: "Cão de Castro Laboreiro" },
    { label: "Cão de Gado Transmontano", value: "Cão de Gado Transmontano" },
    { label: "Cão Fila de São Miguel", value: "Cão Fila de São Miguel" },
    { label: "Cardigan Welsh Corgi", value: "Cardigan Welsh Corgi" },
    { label: "Carea Castellano Manchego", value: ",Carea Castellano Manchego" },
    { label: "Carea Leonés", value: "Carea Leonés" },
    { label: "Carolina Dog", value: "Carolina Dog" },
    { label: "Carpathian Shepherd Dog", value: "Carpathian Shepherd Dog" },
    { label: "Catahoula Leopard Dog", value: "Catahoula Leopard Dog" },
    { label: "Catalan Sheepdog", value: "Catalan Sheepdog" },
    { label: "Caucasian Shepherd Dog", value: "Caucasian Shepherd Dog" },
    { label: "Cavalier King Charles Spaniel", value: "Cavalier King Charles Spaniel" },
    { label: "Central Asian Shepherd Dog", value: "Central Asian Shepherd Dog" },
    { label: "Cesky Fousek", value: "Cesky Fousek" },
    { label: "Cesky Terrier", value: "Cesky Terrier" },
    { label: "Chesapeake Bay Retriever", value: "Chesapeake Bay Retriever" },
    { label: "Chien Français Blanc et Noir", value: "Chien Français Blanc et Noir" },
    { label: "Chien Français Blanc et Orange", value: "Chien Français Blanc et Orange" },
    { label: "Chien Français Tricolore", value: "Chien Français Tricolore" },
    { label: "Chihuahua (dog)|Chihuahua", value: "Chihuahua (dog)|Chihuahua" },
    { label: "Chilean Terrier", value: "Chilean Terrier" },
    { label: "Chinese Chongqing Dog", value: "Chinese Chongqing Dog" },
    { label: "Chinese Crested Dog", value: "Chinese Crested Dog" },
    { label: "Chinook (dog)|Chinook", value: "Chinook (dog)|Chinook" },
    { label: "Chippiparai", value: "Chippiparai" },
    { label: "Chow Chow", value: "Chow Chow" },
    { label: "Cimarrón Uruguayo", value: "Cimarrón Uruguayo" },
    { label: "Cirneco dell'Etna", value: "Cirneco dell'Etna" },
    { label: "Clumber Spaniel", value: "Clumber Spaniel" },
    { label: "Combai", value: "Combai" },
    { label: "Colombian fino hound", value: "Colombian fino hound" },
    { label: "Coton de Tulear", value: "Coton de Tulear" },
    { label: "Cretan Hound", value: "Cretan Hound" },
    { label: "Croatian Sheepdog", value: "Croatian Sheepdog" },
    { label: "Curly Coated Retriever|Curly-Coated Retriever", value: "Curly Coated Retriever|Curly-Coated Retriever" },
    { label: "Cursinu", value: "Cursinu" },
    { label: "Czechoslovakian Wolfdog", value: "Czechoslovakian Wolfdog" },
    { label: "Dachshund", value: "Dachshund" },
    { label: "Dalmatian (dog)|Dalmatian", value: "Dalmatian (dog)|Dalmatian" },
    { label: "Dandie Dinmont Terrier", value: "Dandie Dinmont Terrier" },
    { label: "Danish-Swedish Farmdog", value: "Danish-Swedish Farmdog" },
    { label: "Denmark Feist", value: "Denmark Feist" },
    { label: "Dingo, (sometimes considered a breed of, and sometimes a species separate from, the domestic dog", value: "Dingo, (sometimes considered a breed of, and sometimes a species separate from, the domestic dog" },
    { label: "Dobermann|Doberman Pinscher", value: "Dobermann|Doberman Pinscher" },
    { label: "Dogo Argentino", value: "Dogo Argentino" },
    { label: "Guatemalan Dogo|Dogo Guatemalteco", value: "Guatemalan Dogo|Dogo Guatemalteco" },
    { label: "Dogo Sardesco", value: "Dogo Sardesco" },
    { label: "Brazilian Dogo|Dogue Brasileiro", value: "Brazilian Dogo|Dogue Brasileiro" },
    { label: "Dogue de Bordeaux", value: "Dogue de Bordeaux" },
    { label: "Drentse Patrijshond", value: "Drentse Patrijshond" },
    { label: "Drever", value: "Drever" },
    { label: "Dunker", value: "Dunker" },
    { label: "Dutch Shepherd", value: "Dutch Shepherd" },
    { label: "Dutch Smoushond", value: "Dutch Smoushond" },
    { label: "East Siberian Laika", value: "East Siberian Laika" },
    { label: "East-European Shepherd|East European Shepherd", value: "East-European Shepherd|East European Shepherd" },
    { label: "English Cocker Spaniel", value: "English Cocker Spaniel" },
    { label: "English Foxhound", value: "English Foxhound" },
    { label: "English Mastiff", value: "English Mastiff" },
    { label: "English Setter", value: "English Setter" },
    { label: "English Shepherd", value: "English Shepherd" },
    { label: "English Springer Spaniel", value: "English Springer Spaniel" },
    { label: "English Toy Terrier (Black & Tan)", value: "English Toy Terrier (Black & Tan)" },
    { label: "Entlebucher Mountain Dog", value: "Entlebucher Mountain Dog" },
    { label: "Estonian Hound", value: "Estonian Hound" },
    { label: "Estrela Mountain Dog", value: "Estrela Mountain Dog" },
    { label: "Eurasier", value: "Eurasier" },
    { label: "Field Spaniel", value: "Field Spaniel" },
    { label: "Fila Brasileiro", value: "Fila Brasileiro" },
    { label: "Finnish Hound", value: "Finnish Hound" },
    { label: "Finnish Lapphund", value: "Finnish Lapphund" },
    { label: "Finnish Spitz", value: "Finnish Spitz" },
    { label: "Flat-coated Retriever|Flat-Coated Retriever", value: "Flat-coated Retriever|Flat-Coated Retriever" },
    { label: "French Bulldog", value: "French Bulldog" },
    { label: "French Spaniel", value: "French Spaniel" },
    { label: "Galgo Español", value: "Galgo Español" },
    { label: "Can de Palleiro|Galician Shepherd Dog", value: "Can de Palleiro|Galician Shepherd Dog" },
    { label: "Garafian Shepherd", value: "Garafian Shepherd" },
    { label: "Gascon Saintongeois", value: "Gascon Saintongeois" },
    { label: "Georgian Shepherd", value: "Georgian Shepherd" },
    { label: "German Hound", value: "German Hound" },
    { label: "German Longhaired Pointer", value: "German Longhaired Pointer" },
    { label: "German Pinscher", value: "German Pinscher" },
    { label: "Stichelhaar|German Roughhaired Pointer", value: "Stichelhaar|German Roughhaired Pointer" },
    { label: "German Shepherd|German Shepherd Dog", value: "German Shepherd|German Shepherd Dog" },
    { label: "German Shorthaired Pointer", value: "German Shorthaired Pointer" },
    { label: "German Spaniel", value: "German Spaniel" },
    { label: "German Spitz", value: "German Spitz" },
    { label: "German Wirehaired Pointer", value: "German Wirehaired Pointer" },
    { label: "Giant Schnauzer", value: "Giant Schnauzer" },
    { label: "Glen of Imaal Terrier", value: "Glen of Imaal Terrier" },
    { label: "Golden Retriever", value: "Golden Retriever" },
    { label: "Gończy Polski", value: "Gończy Polski" },
    { label: "Gordon Setter", value: "Gordon Setter" },
    { label: "Grand Anglo-Français Blanc et Noir", value: "Grand Anglo-Français Blanc et Noir" },
    { label: "Grand Anglo-Français Blanc et Orange", value: "Grand Anglo-Français Blanc et Orange" },
    { label: "Grand Anglo-Français Tricolore", value: "Grand Anglo-Français Tricolore" },
    { label: "Grand Basset Griffon Vendéen", value: "Grand Basset Griffon Vendéen" },
    { label: "Grand Bleu de Gascogne", value: "Grand Bleu de Gascogne" },
    { label: "Grand Griffon Vendéen", value: "Grand Griffon Vendéen" },
    { label: "Great Dane", value: "Great Dane" },
    { label: "Greater Swiss Mountain Dog", value: "Greater Swiss Mountain Dog" },
    { label: "Greek Harehound", value: "Greek Harehound" },
    { label: "Greek Shepherd", value: "Greek Shepherd" },
    { label: "Greenland Dog", value: "Greenland Dog" },
    { label: "Greyhound", value: "Greyhound" },
    { label: "Griffon Bleu de Gascogne", value: "Griffon Bleu de Gascogne" },
    { label: "Griffon Fauve de Bretagne", value: "Griffon Fauve de Bretagne" },
    { label: "Griffon Nivernais", value: "Griffon Nivernais" },
    { label: "Gull Dong", value: "Gull Dong" },
    { label: "Gull Terrier", value: "Gull Terrier" },
    { label: "Hällefors Elkhound", value: "Hällefors Elkhound" },
    { label: "Hamiltonstövare", value: "Hamiltonstövare" },
    { label: "Hanover Hound", value: "Hanover Hound" },
    { label: "Harrier (dog)|Harrier", value: "Harrier (dog)|Harrier" },
    { label: "Havanese dog|Havanese", value: "Havanese dog|Havanese" },
    { label: "Hierran Wolfdog", value: "Hierran Wolfdog" },
    { label: "Hokkaido (dog)|Hokkaido", value: "Hokkaido (dog)|Hokkaido" },
    { label: "Hortaya borzaya", value: "Hortaya borzaya" },
    { label: "Hovawart", value: "Hovawart" },
    { label: "Huntaway", value: "Huntaway" },
    { label: "Hygen Hound", value: "Hygen Hound" },
    { label: "Ibizan Hound", value: "Ibizan Hound" },
    { label: "Icelandic Sheepdog", value: "Icelandic Sheepdog" },
    { label: "Indian pariah dog", value: "Indian pariah dog" },
    { label: "Indian Spitz", value: "Indian Spitz" },
    { label: "Irish Red and White Setter", value: "Irish Red and White Setter" },
    { label: "Irish Setter", value: "Irish Setter" },
    { label: "Irish Terrier", value: "Irish Terrier" },
    { label: "Irish Water Spaniel", value: "Irish Water Spaniel" },
    { label: "Irish Wolfhound", value: "Irish Wolfhound" },
    { label: "Istrian Coarse-haired Hound", value: "Istrian Coarse-haired Hound" },
    { label: "Istrian Shorthaired Hound", value: "Istrian Shorthaired Hound" },
    { label: "Italian Greyhound", value: "Italian Greyhound" },
    { label: "Jack Russell Terrier", value: "Jack Russell Terrier" },
    { label: "Jagdterrier", value: "Jagdterrier" },
    { label: "Japanese Chin", value: "Japanese Chin" },
    { label: "Japanese Spitz", value: "Japanese Spitz" },
    { label: "Japanese Terrier", value: "Japanese Terrier" },
    { label: "Korean Jindo|Jindo", value: "Korean Jindo|Jindo" },
    { label: "Jonangi", value: "Jonangi" },
    { label: "Kai Ken", value: "Kai Ken" },
    { label: "Kangal Shepherd Dog", value: "Kangal Shepherd Dog" },
    { label: "Kanni", value: "Kanni" },
    { label: "Karakachan dog", value: "Karakachan dog" },
    { label: "Karelian Bear Dog", value: "Karelian Bear Dog" },
    { label: "Karst Shepherd", value: "Karst Shepherd" },
    { label: "Keeshond", value: "Keeshond" },
    { label: "Kerry Beagle", value: "Kerry Beagle" },
    { label: "Kerry Blue Terrier", value: "Kerry Blue Terrier" },
    { label: "King Charles Spaniel", value: "King Charles Spaniel" },
    { label: "King Shepherd", value: "King Shepherd" },
    { label: "Kintamani (dog)|Kintamani", value: "Kintamani (dog)|Kintamani" },
    { label: "Kishu", value: "Kishu" },
    { label: "Kokoni", value: "Kokoni" },
    { label: "Komondor", value: "Komondor" },
    { label: "Kooikerhondje", value: "Kooikerhondje" },
    { label: "Koolie", value: "Koolie" },
    { label: "Koyun dog", value: "Koyun dog" },
    { label: "Kromfohrländer", value: "Kromfohrländer" },
    { label: "Kuchi dog|Kuchi", value: "Kuchi dog|Kuchi" },
    { label: "Kuvasz", value: "Kuvasz" },
    { label: "Labrador Retriever", value: "Labrador Retriever" },
    { label: "Lagotto Romagnolo", value: "Lagotto Romagnolo" },
    { label: "Lakeland Terrier", value: "Lakeland Terrier" },
    { label: "Lancashire Heeler", value: "Lancashire Heeler" },
    { label: "Landseer (dog)|Landseer", value: "Landseer (dog)|Landseer" },
    { label: "Lapponian Herder", value: "Lapponian Herder" },
    { label: "Large Münsterländer", value: "Large Münsterländer" },
    { label: "Leonberger", value: "Leonberger" },
    { label: "Lhasa Apso", value: "Lhasa Apso" },
    { label: "Lithuanian Hound", value: "Lithuanian Hound" },
    { label: "Löwchen", value: "Löwchen" },
    { label: "Lupo Italiano", value: "Lupo Italiano" },
    { label: "Mackenzie River husky", value: "Mackenzie River husky" },
    { label: "Magyar agár", value: "Magyar agár" },
    { label: "Mahratta Greyhound", value: "Mahratta Greyhound" },
    { label: "Maltese (dog)|Maltese", value: "Maltese (dog)|Maltese" },
    { label: "Manchester Terrier", value: "Manchester Terrier" },
    { label: "Maremmano-Abruzzese Sheepdog", value: "Maremmano-Abruzzese Sheepdog" },
    { label: "McNab dog", value: "McNab dog" },
    { label: "Miniature American Shepherd", value: "Miniature American Shepherd" },
    { label: "Miniature Bull Terrier", value: "Miniature Bull Terrier" },
    { label: "Miniature Fox Terrier", value: "Miniature Fox Terrier" },
    { label: "Miniature Pinscher", value: "Miniature Pinscher" },
    { label: "Miniature Schnauzer", value: "Miniature Schnauzer" },
    { label: "Molossus of Epirus", value: "Molossus of Epirus" },
    { label: "Montenegrin Mountain Hound", value: "Montenegrin Mountain Hound" },
    { label: "Mountain Cur", value: "Mountain Cur" },
    { label: "Mountain Feist", value: "Mountain Feist" },
    { label: "Mucuchies", value: "Mucuchies" },
    { label: "Mudhol Hound", value: "Mudhol Hound" },
    { label: "Mudi", value: "Mudi" },
    { label: "Neapolitan Mastiff", value: "Neapolitan Mastiff" },
    { label: "New Guinea singing dog", value: "New Guinea singing dog" },
    { label: "New Zealand Heading Dog", value: "New Zealand Heading Dog" },
    { label: "Newfoundland (dog)|Newfoundland", value: "Newfoundland (dog)|Newfoundland" },
    { label: "Norfolk Terrier", value: "Norfolk Terrier" },
    { label: "Norrbottenspets", value: "Norrbottenspets" },
    { label: "Northern Inuit Dog", value: "Northern Inuit Dog" },
    { label: "Norwegian Buhund", value: "Norwegian Buhund" },
    { label: "Norwegian Elkhound", value: "Norwegian Elkhound" },
    { label: "Norwegian Lundehund", value: "Norwegian Lundehund" },
    { label: "Norwich Terrier", value: "Norwich Terrier" },
    { label: "Nova Scotia Duck Tolling Retriever", value: "Nova Scotia Duck Tolling Retriever" },
    { label: "Old Croatian Sighthound", value: "Old Croatian Sighthound" },
    { label: "Old Danish Pointer", value: "Old Danish Pointer" },
    { label: "Old English Sheepdog", value: "Old English Sheepdog" },
    { label: "Old English Terrier", value: "Old English Terrier" },
    { label: "Olde English Bulldogge", value: "Olde English Bulldogge" },
    { label: "Original Fila Brasileiro", value: "Original Fila Brasileiro" },
    { label: "Otterhound", value: "Otterhound" },
    { label: "Pachon Navarro", value: "Pachon Navarro" },
    { label: "Paisley Terrier", value: "Paisley Terrier" },
    { label: "Papillon (dog)|Papillon", value: "Papillon (dog)|Papillon" },
    { label: "Parson Russell Terrier", value: "Parson Russell Terrier" },
    { label: "Pastore della Lessinia e del Lagorai", value: "Pastore della Lessinia e del Lagorai" },
    { label: "Patagonian Sheepdog", value: "Patagonian Sheepdog" },
    { label: "Patterdale Terrier", value: "Patterdale Terrier" },
    { label: "Pekingese", value: "Pekingese" },
    { label: "Pembroke Welsh Corgi", value: "Pembroke Welsh Corgi" },
    { label: "Perro Majorero", value: "Perro Majorero" },
    { label: "Majorca Shepherd Dog|Perro de Pastor Mallorquin", value: "Majorca Shepherd Dog|Perro de Pastor Mallorquin" },
    { label: "Perro de Presa Canario", value: "Perro de Presa Canario" },
    { label: "Ca de Bou|Perro de Presa Mallorquin", value: "Ca de Bou|Perro de Presa Mallorquin" },
    { label: "Peruvian Hairless Dog|Peruvian Inca Orchid", value: "Peruvian Hairless Dog|Peruvian Inca Orchid" },
    { label: "Petit Basset Griffon Vendéen", value: "Petit Basset Griffon Vendéen" },
    { label: "Petit Bleu de Gascogne", value: "Petit Bleu de Gascogne" },
    { label: "Phalène", value: "Phalène" },
    { label: "Pharaoh Hound", value: "Pharaoh Hound" },
    { label: "Phu Quoc Ridgeback", value: "Phu Quoc Ridgeback" },
    { label: "Picardy Spaniel", value: "Picardy Spaniel" },
    { label: "Plummer Terrier", value: "Plummer Terrier" },
    { label: "Plott Hound", value: "Plott Hound" },
    { label: "Podenco Canario", value: "Podenco Canario" },
    { label: "Pointer (dog breed)|Pointer", value: "Pointer (dog breed)|Pointer" },
    { label: "Poitevin hound|Poitevin", value: "Poitevin hound|Poitevin" },
    { label: "Polish Greyhound", value: "Polish Greyhound" },
    { label: "Polish Hound", value: "Polish Hound" },
    { label: "Polish Lowland Sheepdog", value: "Polish Lowland Sheepdog" },
    { label: "Polish Tatra Sheepdog", value: "Polish Tatra Sheepdog" },
    { label: "Pomeranian (dog)|Pomeranian", value: "Pomeranian (dog)|Pomeranian" },
    { label: "Pont-Audemer Spaniel", value: "Pont-Audemer Spaniel" },
    { label: "Poodle", value: "Poodle" },
    { label: "Porcelaine", value: "Porcelaine" },
    { label: "Portuguese Podengo", value: "Portuguese Podengo" },
    { label: "Portuguese Pointer", value: "Portuguese Pointer" },
    { label: "Portuguese Water Dog", value: "Portuguese Water Dog" },
    { label: "Posavac Hound", value: "Posavac Hound" },
    { label: "Pražský Krysařík", value: "Pražský Krysařík" },
    { label: "Pshdar dog", value: "Pshdar dog" },
    { label: "Pudelpointer", value: "Pudelpointer" },
    { label: "Pug", value: "Pug" },
    { label: "Puli dog|Puli", value: "Puli dog|Puli" },
    { label: "Pumi (dog)|Pumi", value: "Pumi (dog)|Pumi" },
    { label: "Pungsan dog", value: "Pungsan dog" },
    { label: "Pyrenean Mastiff", value: "Pyrenean Mastiff" },
    { label: "Pyrenean Mountain Dog", value: "Pyrenean Mountain Dog" },
    { label: "Pyrenean Shepherd", value: "Pyrenean Shepherd" },
    { label: "Rafeiro do Alentejo", value: "Rafeiro do Alentejo" },
    { label: "Rajapalayam (dog)|Rajapalayam", value: "Rajapalayam (dog)|Rajapalayam" },
    { label: "Rampur Greyhound", value: "Rampur Greyhound" },
    { label: "Rat Terrier", value: "Rat Terrier" },
    { label: "Ratonero Bodeguero Andaluz", value: "Ratonero Bodeguero Andaluz" },
    { label: "Majorca Ratter|Ratonero Mallorquin", value: "Majorca Ratter|Ratonero Mallorquin" },
    { label: "Ratonero Murciano de Huerta", value: "Ratonero Murciano de Huerta" },
    { label: "Ratonero Valenciano", value: "Ratonero Valenciano" },
    { label: "Redbone Coonhound", value: "Redbone Coonhound" },
    { label: "Rhodesian Ridgeback", value: "Rhodesian Ridgeback" },
    { label: "Romanian Mioritic Shepherd Dog", value: "Romanian Mioritic Shepherd Dog" },
    { label: "Romanian Raven Shepherd Dog", value: "Romanian Raven Shepherd Dog" },
    { label: "Rottweiler", value: "Rottweiler" },
    { label: "Rough Collie", value: "Rough Collie" },
    { label: "Russian Spaniel", value: "Russian Spaniel" },
    { label: "Russkiy Toy|Russian Toy", value: "Russkiy Toy|Russian Toy" },
    { label: "Russo-European Laika", value: "Russo-European Laika" },
    { label: "Russell Terrier", value: "Russell Terrier" },
    { label: "Saarloos wolfdog|Saarloos Wolfdog", value: "Saarloos wolfdog|Saarloos Wolfdog" },
    { label: "Sabueso Español", value: "Sabueso Español" },
    { label: "St. Bernard (dog)|Saint Bernard", value: "St. Bernard (dog)|Saint Bernard" },
    { label: "St. Hubert Jura Hound|Saint Hubert Jura Hound", value: "St. Hubert Jura Hound|Saint Hubert Jura Hound" },
    { label: "Saint-Usuge Spaniel", value: "Saint-Usuge Spaniel" },
    { label: "Saluki", value: "Saluki" },
    { label: "Samoyed (dog)|Samoyed", value: "Samoyed (dog)|Samoyed" },
    { label: "Sapsali", value: "Sapsali" },
    { label: "Sarabi dog", value: "Sarabi dog" },
    { label: "Šarplaninac", value: "Šarplaninac" },
    { label: "Schapendoes", value: "Schapendoes" },
    { label: "Schillerstövare", value: "Schillerstövare" },
    { label: "Schipperke", value: "Schipperke" },
    { label: "Schweizer Laufhund", value: "Schweizer Laufhund" },
    { label: "Schweizerischer Niederlaufhund", value: "Schweizerischer Niederlaufhund" },
    { label: "Scottish Deerhound", value: "Scottish Deerhound" },
    { label: "Scottish Terrier", value: "Scottish Terrier" },
    { label: "Sealyham Terrier", value: "Sealyham Terrier" },
    { label: "Segugio Italiano", value: "Segugio Italiano" },
    { label: "Seppala Siberian Sleddog", value: "Seppala Siberian Sleddog" },
    { label: "Serbian Hound", value: "Serbian Hound" },
    { label: "Serbian Tricolour Hound", value: "Serbian Tricolour Hound" },
    { label: "Serrano Bulldog", value: "Serrano Bulldog" },
    { label: "Shar Pei", value: "Shar Pei" },
    { label: "Shetland Sheepdog", value: "Shetland Sheepdog" },
    { label: "Shiba Inu", value: "Shiba Inu" },
    { label: "Shih Tzu", value: "Shih Tzu" },
    { label: "Shikoku (dog)|Shikoku", value: "Shikoku (dog)|Shikoku" },
    { label: "Shiloh Shepherd dog|Shiloh Shepherd", value: "Shiloh Shepherd dog|Shiloh Shepherd" },
    { label: "Siberian Husky", value: "Siberian Husky" },
    { label: "Silken Windhound", value: "Silken Windhound" },
    { label: "Australian Silky Terrier|Silky Terrier", value: "Australian Silky Terrier|Silky Terrier" },
    { label: "Sinhala Hound", value: "Sinhala Hound" },
    { label: "Skye Terrier", value: "Skye Terrier" },
    { label: "Sloughi", value: "Sloughi" },
    { label: "Slovak Rough-haired Pointer|Slovakian Wirehaired Pointer", value: "Slovak Rough-haired Pointer|Slovakian Wirehaired Pointer" },
    { label: "Slovak Cuvac|Slovenský Cuvac", value: "Slovak Cuvac|Slovenský Cuvac" },
    { label: "Slovenský kopov|Slovenský Kopov", value: "Slovenský kopov|Slovenský Kopov" },
    { label: "Smaland Hound|Smalandstövare", value: "Smaland Hound|Smalandstövare" },
    { label: "Small Greek domestic dog", value: "Small Greek domestic dog" },
    { label: "Small Münsterländer", value: "Small Münsterländer" },
    { label: "Smooth Collie", value: "Smooth Collie" },
    { label: "Smooth Fox Terrier", value: "Smooth Fox Terrier" },
    { label: "Soft-Coated Wheaten Terrier", value: "Soft-Coated Wheaten Terrier" },
    { label: "South Russian Ovcharka", value: "South Russian Ovcharka" },
    { label: "Spanish Mastiff", value: "Spanish Mastiff" },
    { label: "Spanish Water Dog", value: "Spanish Water Dog" },
    { label: "Spinone Italiano", value: "Spinone Italiano" },
    { label: "Sporting Lucas Terrier", value: "Sporting Lucas Terrier" },
    { label: "Stabyhoun", value: "Stabyhoun" },
    { label: "Staffordshire Bull Terrier", value: "Staffordshire Bull Terrier" },
    { label: "Standard Schnauzer", value: "Standard Schnauzer" },
    { label: "Stephens Cur", value: "Stephens Cur" },
    { label: "Styrian Coarse-haired Hound", value: "Styrian Coarse-haired Hound" },
    { label: "Sussex Spaniel", value: "Sussex Spaniel" },
    { label: "Jämthund|Swedish Elkhound", value: "Jämthund|Swedish Elkhound" },
    { label: "Swedish Lapphund", value: "Swedish Lapphund" },
    { label: "Swedish Vallhund", value: "Swedish Vallhund" },
    { label: "Tahltan Bear Dog", value: "Tahltan Bear Dog" },
    { label: "Taigan", value: "Taigan" },
    { label: "Taiwan Dog", value: "Taiwan Dog" },
    { label: "Tamaskan Dog", value: "Tamaskan Dog" },
    { label: "Teddy Roosevelt Terrier", value: "Teddy Roosevelt Terrier" },
    { label: "Telomian", value: "Telomian" },
    { label: "Tenterfield Terrier", value: "Tenterfield Terrier" },
    { label: "Brazilian Terrier|Terrier Brasileiro", value: "Brazilian Terrier|Terrier Brasileiro" },
    { label: "Thai Bangkaew Dog", value: "Thai Bangkaew Dog" },
    { label: "Thai Ridgeback", value: "Thai Ridgeback" },
    { label: "Tibetan Mastiff", value: "Tibetan Mastiff" },
    { label: "Tibetan Spaniel", value: "Tibetan Spaniel" },
    { label: "Tibetan Terrier", value: "Tibetan Terrier" },
    { label: "Tornjak", value: "Tornjak" },
    { label: "Tosa (dog)|Tosa", value: "Tosa (dog)|Tosa" },
    { label: "Toy Fox Terrier", value: "Toy Fox Terrier" },
    { label: "Toy Manchester Terrier", value: "Toy Manchester Terrier" },
    { label: "Transylvanian Hound", value: "Transylvanian Hound" },
    { label: "Treeing Cur", value: "Treeing Cur" },
    { label: "Treeing Feist", value: "Treeing Feist" },
    { label: "Treeing Tennessee Brindle", value: "Treeing Tennessee Brindle" },
    { label: "Treeing Walker Coonhound", value: "Treeing Walker Coonhound" },
    { label: "Trigg Hound", value: "Trigg Hound" },
    { label: "Tyrolean Hound", value: "Tyrolean Hound" },
    { label: "Vikhan", value: "Vikhan" },
    { label: "Villano de Las Encartaciones", value: "Villano de Las Encartaciones" },
    { label: "Villanuco de Las Encartaciones", value: "Villanuco de Las Encartaciones" },
    { label: "Vizsla", value: "Vizsla" },
    { label: "Volpino Italiano", value: "Volpino Italiano" },
    { label: "Weimaraner", value: "Weimaraner" },
    { label: "Welsh Sheepdog", value: "Welsh Sheepdog" },
    { label: "Welsh Springer Spaniel", value: "Welsh Springer Spaniel" },
    { label: "Welsh Terrier", value: "Welsh Terrier" },
    { label: "West Highland White Terrier", value: "West Highland White Terrier" },
    { label: "West Siberian Laika", value: "West Siberian Laika" },
    { label: "Westphalian Dachsbracke", value: "Westphalian Dachsbracke" },
    { label: "Wetterhoun", value: "Wetterhoun" },
    { label: "Whippet", value: "Whippet" },
    { label: "White Shepherd", value: "White Shepherd" },
    { label: "White Swiss Shepherd Dog", value: "White Swiss Shepherd Dog" },
    { label: "Wire Fox Terrier", value: "Wire Fox Terrier" },
    { label: "Wirehaired Pointing Griffon", value: "Wirehaired Pointing Griffon" },
    { label: "Wirehaired Vizsla", value: "Wirehaired Vizsla" },
    { label: "Xiasi Dog", value: "Xiasi Dog" },
    { label: "Mexican Hairless Dog|Xoloitzcuintli", value: "Mexican Hairless Dog|Xoloitzcuintli" },
    { label: "Yakutian Laika", value: "Yakutian Laika" },
    { label: "Yorkshire Terrier", value: "Yorkshire Terrier" },
    ];

    this.catBreeds=[{ label:"Abyssinian	", value:"Abyssinian"},
    { label:"Aegean	", value:"Aegean"},
    { label:"American Bobtail	", value:"American Bobtail"},
    { label:"American Curl	", value:"American Curl"},
    { label:"American Ringtail	", value:"American Ringtail"},
    { label:"American Shorthair	", value:"American Shorthair"},
    { label:"American Wirehair	", value:"American Wirehair"},
    { label:"Aphrodite Giant	", value:"Aphrodite Giant"},
    { label:"Arabian Mau	", value:"Arabian Mau"},
    { label:"Asian cat	", value:"Asian cat"},
    { label:"Asian Semi-longhair	", value:"Asian Semi-longhair"},
    { label:"Australian Mist	", value:"Australian Mist"},
    { label:"Balinese	", value:"Balinese"},
    { label:"Bambino	", value:"Bambino"},
    { label:"Bengal	", value:"Bengal"},
    { label:"Birman	", value:"Birman"},
    { label:"Bombay	", value:"Bombay"},
    { label:"Brazilian Shorthair	", value:"Brazilian Shorthair"},
    { label:"British Longhair	", value:"British Longhair"},
    { label:"British Shorthair	", value:"British Shorthair"},
    { label:"Burmese	", value:"Burmese"},
    { label:"Burmilla	", value:"Burmilla"},
    { label:"California Spangled	", value:"California Spangled"},
    { label:"Chantilly-Tiffany	", value:"Chantilly-Tiffany"},
    { label:"Chartreux	", value:"Chartreux"},
    { label:"Chausie	", value:"Chausie"},
    { label:"Colorpoint Shorthair	", value:"Colorpoint Shorthair"},
    { label:"Cornish Rex	", value:"Cornish Rex"},
    { label:"Cymric, Manx Longhair or Long-haired Manx[b]	", value:"Cymric, Manx Longhair or Long-haired Manx[b]"},
    { label:"Cyprus	", value:"Cyprus"},
    { label:"Devon Rex	", value:"Devon Rex"},
    { label:"Donskoy or	", value:"Donskoy or"},
    { label:"Don Sphynx	", value:"Don Sphynx"},
    { label:"Dragon Li or	", value:"Dragon Li or"},
    { label:"Chinese Li Hua	", value:"Chinese Li Hua"},
    { label:"Dwelf	", value:"Dwelf"},
    { label:"Egyptian Mau	", value:"Egyptian Mau"},
    { label:"European Shorthair	", value:"European Shorthair"},
    { label:"Exotic Shorthair	", value:"Exotic Shorthair"},
    { label:"Foldex[6]	", value:"Foldex[6]"},
    { label:"German Rex	", value:"German Rex"},
    { label:"Havana Brown	", value:"Havana Brown"},
    { label:"Highlander	", value:"Highlander"},
    { label:"Himalayan or	", value:"Himalayan or"},
    { label:"Colorpoint Persian[d]	", value:"Colorpoint Persian[d]"},
    { label:"Japanese Bobtail	", value:"Japanese Bobtail"},
    { label:"Javanese or	", value:"Javanese or"},
    { label:"Colorpoint Longhair[f]	", value:"Colorpoint Longhair[f]"},
    { label:"Kanaani	", value:"Kanaani"},
    { label:"Khao Manee	", value:"Khao Manee"},
    { label:"Kinkalow	", value:"Kinkalow"},
    { label:"Korat	", value:"Korat"},
    { label:"Korean Bobtail	", value:"Korean Bobtail"},
    { label:"Korn Ja	", value:"Korn Ja"},
    { label:"Kurilian Bobtail or	", value:"Kurilian Bobtail or"},
    { label:"Kuril Islands Bobtail	", value:"Kuril Islands Bobtail"},
    { label:"Lambkin	", value:"Lambkin"},
    { label:"LaPerm	", value:"LaPerm"},
    { label:"Lykoi	", value:"Lykoi"},
    { label:"Maine Coon	", value:"Maine Coon"},
    { label:"Manx	", value:"Manx"},
    { label:"Mekong Bobtail	", value:"Mekong Bobtail"},
    { label:"Minskin	", value:"Minskin"},
    { label:"Napoleon	", value:"Napoleon"},
    { label:"Munchkin	", value:"Munchkin"},
    { label:"Nebelung	", value:"Nebelung"},
    { label:"Norwegian Forest Cat	", value:"Norwegian Forest Cat"},
    { label:"Ocicat	", value:"Ocicat"},
    { label:"Ojos Azules	", value:"Ojos Azules"},
    { label:"Oregon Rex	", value:"Oregon Rex"},
    { label:"Oriental Bicolor	", value:"Oriental Bicolor"},
    { label:"Oriental Longhair[g]	", value:"Oriental Longhair[g]"},
    { label:"Oriental Shorthair[g]	", value:"Oriental Shorthair[g]"},
    { label:"Persian (modern)	", value:"Persian (modern)"},
    { label:"Persian (traditional)	", value:"Persian (traditional)"},
    { label:"Peterbald	", value:"Peterbald"},
    { label:"Pixie-bob	", value:"Pixie-bob"},
    { label:"Ragamuffin or	", value:"Ragamuffin or"},
    { label:"Liebling (obsolete)	", value:"Liebling (obsolete)"},
    { label:"Ragdoll	", value:"Ragdoll"},
    { label:"Raas	", value:"Raas"},
    { label:"Russian Blue	", value:"Russian Blue"},
    { label:"Russian White, Russian Black and Russian Tabby	", value:"Russian White, Russian Black and Russian Tabby"},
    { label:"Sam Sawet	", value:"Sam Sawet"},
    { label:"Savannah	", value:"Savannah"},
    { label:"Scottish Fold	", value:"Scottish Fold"},
    { label:"Selkirk Rex	", value:"Selkirk Rex"},
    { label:"Serengeti	", value:"Serengeti"},
    { label:"Serrade Petit	", value:"Serrade Petit"},
    { label:"Siamese (modern)	", value:"Siamese (modern)"},
    { label:"(for traditional, see Thai below)	", value:"(for traditional, see Thai below)"},
    { label:"Siberian or	", value:"Siberian or"},
    { label:"Siberian Forest Cat;	", value:"Siberian Forest Cat;"},
    { label:"Neva Masquerade (colorpoint variety)	", value:"Neva Masquerade (colorpoint variety)"},
    { label:"Singapura	", value:"Singapura"},
    { label:"Snowshoe	", value:"Snowshoe"},
    { label:"Sokoke	", value:"Sokoke"},
    { label:"Somali	", value:"Somali"},
    { label:"Sphynx	", value:"Sphynx"},
    { label:"Suphalak	", value:"Suphalak"},
    { label:"Thai or	", value:"Thai or"},
    { label:"Traditional, Classic, or Old-style Siamese;	", value:"Traditional, Classic, or Old-style Siamese;"},
    { label:"Wichien Maat[h]	", value:"Wichien Maat[h]"},
    { label:"Thai Lilac, Thai Blue Point and Thai Lilac Point	", value:"Thai Lilac, Thai Blue Point and Thai Lilac Point"},
    { label:"Tonkinese	", value:"Tonkinese"},
    { label:"Toyger	", value:"Toyger"},
    { label:"Turkish Angora	", value:"Turkish Angora"},
    { label:"Turkish Van	", value:"Turkish Van"},
    { label:"Turkish Vankedisi	", value:"Turkish Vankedisi"},
    { label:"Ukrainian Levkoy	", value:"Ukrainian Levkoy"},
    { label:"Wila Krungthep	", value:"Wila Krungthep"},
    { label:"York Chocolate	", value:"York Chocolate"},
    ];
  }

  returnAllDogBreeds() {
    return this.dogBreeds;
  }

  returnAllCatBreeds() {
    return this.catBreeds;
  }

  returnAllTypes()
  {
    return this.types;
  }

}
